---
- name: Create Redis data directory
  ansible.builtin.file:
    path: "{{ siem_data_dir }}/redis"
    state: directory
    owner: "999"  # redis user in redis:alpine Docker image
    group: "1000"
    mode: "0755"

- name: Template Redis Docker Compose file
  ansible.builtin.template:
    src: docker-compose.redis.yml.j2
    dest: "{{ siem_config_dir }}/docker-compose.redis.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart redis

- name: Pull and start Redis
  ansible.builtin.command:
    cmd: docker compose -f {{ siem_config_dir }}/docker-compose.redis.yml up -d --pull always
  register: redis_up
  changed_when: >-
    'Started' in redis_up.stdout or
    'Created' in redis_up.stdout or
    'Pulled' in redis_up.stdout
  ignore_errors: "{{ ansible_check_mode }}"
