---
- name: Install redis-server
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: true

- name: Template Redis config
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0640"
  ignore_errors: "{{ ansible_check_mode }}"
  notify: Restart redis

- name: Enable and start redis-server
  ansible.builtin.systemd:
    name: redis-server
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create redis-server systemd drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/system/redis-server.service.d
    state: directory
    mode: "0755"

- name: Add OnFailure drop-in for redis-server
  ansible.builtin.copy:
    content: |
      [Unit]
      OnFailure=notify-ntfy@%n.service
      [Service]
      ExecStartPost=-/bin/systemctl start --no-block notify-ntfy-clear@%N.service
    dest: /etc/systemd/system/redis-server.service.d/ntfy.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd daemon
