[siem_server]
siem_server

[postgresql_server]
postgresql_server

[redis_server]
redis_server

[ntfy_servers]
laf2  ansible_host=10.77.3.202

[nodes]
laf1  ansible_host=laf1.local
laf2  ansible_host=10.77.3.202
