---
- name: Restart postgresql
  ansible.builtin.systemd:
    name: "postgresql@{{ postgresql_version }}-main"
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
