---
- name: Restart redis
  ansible.builtin.systemd:
    name: redis-server
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
